name: habit_flow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1 
  go_router: ^14.8.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true