name: habit_flow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^14.8.1
  shimmer: ^3.0.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  flutter_timezone: ^4.1.0
  supabase_flutter: ^2.5.9
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.14
  hive_ce_generator: ^1.9.0

  freezed: ^3.0.6
  json_serializable: ^6.9.4
  dart_code_linter: ^3.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFNS.ttf
          weight: 400
        - asset: assets/fonts/SFNSItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SFCompact.ttf
          weight: 600
        - asset: assets/fonts/SFCompactItalic.ttf
          weight: 600
          style: italic
